### ISSUE TITLE
support training with c++

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#10574]
## Background
Some system need to train neural network using C++ API of fluid, so fluid need to provide the interface and a demo to do this.

## TODO
- [x] 1. User use Python to describe the network then save the ProgramDesc to disk.
- [x] 2. Add a CPP interface to load the ProgramDesc from disk.
- [x] 3. use CPP Executor to run the ProgramDesc
- [x] 4. Add document

**Comment by jacquesqiao** [comment]
第一阶段已完成
