### ISSUE TITLE
complete distributed lookup table

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#10868]
## Tasks
- [x] distribute lookup table support async training https://github.com/PaddlePaddle/Paddle/pull/10973
- [x] add auto_grown_mutex for selected_rows https://github.com/PaddlePaddle/Paddle/pull/11012
- [x] run dist lookup table on dlnel cluster
- [x] run dist lookup table on paddle cloud
- [ ] support use lookup_sparse_table at local training to support OOV(out of vocabulary) id.
- [ ] suport variant method to initialize non exists ID in the table(Guass, Uniform or zero)

## support deep and wide model
- [x] concat_op support data layer as input https://github.com/PaddlePaddle/Paddle/pull/11527
- [x] support Ftrl optimizer https://github.com/PaddlePaddle/Paddle/pull/11547
- [x] refine prefetch to support multi thread prefetch https://github.com/PaddlePaddle/Paddle/pull/11366 
- [x] add a merge_ids op to replace concat op to merge the result of distribute lookup table. https://github.com/PaddlePaddle/Paddle/pull/11342
- [x] support auc calculate https://github.com/PaddlePaddle/Paddle/pull/11574
- [x] support save/load dist look up table on pserver side. @seiriosPlus https://github.com/PaddlePaddle/Paddle/pull/11490
- [x] fix adam op for selected rows https://github.com/PaddlePaddle/Paddle/pull/11765

**Comment by Yancey1989** [comment]
we can also support OOV(out of vocabulary) with local training, and initialize the parameter of the unknown ID as 0, Gauss or uniform random.

**Comment by jacquesqiao** [comment]
@Yancey1989 Yes, we can support to use lookup_sparse_table at local training.

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
