### ISSUE TITLE
TODO jobs needed by fluid benchmark docker image.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#11091]
- [ ] Need Docker file which builds to `bootstrapper:5000/fluid_benchmark:gpu`
- [ ] The `https://github.com/PaddlePaddle/cloud/blob/develop/docker/paddle_k8s` should be replaced by `/usr/bin/paddle_k8s`   in `bootstrapper:5000/fluid_benchmark:gpu`
- [ ] The `bootstrapper:5000/fluid_benchmark:gpu` should contain dataset need by the supported models
- [ ]  The `bootstrapper:5000/fluid_benchmark:gpu` should contain benchmark Python scripts under `/workspace`
- [ ] The `bootstrapper:5000/fluid_benchmark:gpu` should be placed onto dockerhub and the later should be updated on time.

**Comment by typhoonzero** [comment]
Thanks for reminding, will update this shortly.
