### ISSUE TITLE
Improve Docker Images

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#1630]
Improve the design doc of Docker build  #1627 

- [x] remove book submodule from paddle repo  @gangliao #1631
- [x] add paddle submodule in book repo @gangliao https://github.com/PaddlePaddle/book/pull/218
- [x] paddle dev dockerfile `paddle:<version>-dev` #1598 @typhoonzero 
- [x] paddle production image `paddle:<version>` via paddle dev #1598  @typhoonzero 
- [x] paddle book dockerfile @gongweibao https://github.com/PaddlePaddle/book/pull/220
