### ISSUE TITLE
[Int8v2] Release 1.6 performance regression problem

### ISSUE THREAD

**Issue by bingyanghuang** [PaddlePaddle/Paddle#20532]
Based on Baidu Xeon 6271 tested results, we found that INT8 v2 (post-training quantization) has performance regression problem.  Issue to track until it is solved.
![image](https://user-images.githubusercontent.com/33643817/66657738-ea217980-ec72-11e9-91ba-7c85618f9f5b.png)
@Sand3r- @jczaja Please help solve this problem.

**Comment by grygielski** [comment]
I've made little investigation of that problem and it seems to be mkldnn conv related regression. I've noticed int8 MobileNet-V1 performance regression at 12% level between release/1.5 and release/1.6 branch, VGG16 also slowed down by ~4%. The cause is the commit https://github.com/PaddlePaddle/Paddle/commit/2c32c2d6496be3decd3745d2b47e2f93ea4f3371. However, I haven't noticed any fp32 regression (most models even sped up) between these versions. Also int8 GoogleNet happened to execute less reorders and be faster than in release/1.5.

**For benchmarking I used:** Xeon Gold 6248 CLX architecture
**Test command:** `./paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification --batch_size=1 --paddle_num_threads=1 --repeat=1000 --infer_model=./third_party/inference_demo/int8v2/mobilenetv1/model --infer_data=./third_party/inference_demo/int8v2/data.bin
`

**Comment by bingyanghuang** [comment]
**Our reproduction on Xeon CLX 6248:**
![image](https://user-images.githubusercontent.com/33643817/66725900-82348400-ee68-11e9-9f41-3d7162faa612.png)

**Comment by wozna** [comment]
![image](https://user-images.githubusercontent.com/33838455/66736715-469ab980-ee6a-11e9-87bc-e7096b6ddf15.png)
It's one thread benchmark on CLX 6248.

**Comment by grygielski** [comment]
We found some possible problems and after implementing some fixes I managed to lower int8 mobilenetv1 performance regression to 7%. We are still working to reduce it to 0.

**Comment by Sand3r-** [comment]
> **Test command:** `./paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification --batch_size=1 --paddle_num_threads=1 --repeat=1000 --infer_model=./third_party/inference_demo/int8v2/mobilenetv1/model --infer_data=./third_party/inference_demo/int8v2/data.bin `

@luotao1 We want to fully align with your setup to reproduce the problem.
1. Could you please confirm that you're using:
* the same command as shown above
* the same models publicly available and downloaded with paddle
* small dataset (`data.bin`)
2. And that you compare the difference between v1.5.0 and v1.6.0-rc0 tags?
3. Could you also provide the CMake flags used for building?

**Comment by luotao1** [comment]
@juncaipeng @wzzju

**Comment by bingyanghuang** [comment]
@juncaipeng Could you help rerun the int8v2 benchmark with tag `v1.5.0` on the same server (6271) that you run the Release 1.6 benchmark ?

**Comment by juncaipeng** [comment]
> > **Test command:** `./paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification --batch_size=1 --paddle_num_threads=1 --repeat=1000 --infer_model=./third_party/inference_demo/int8v2/mobilenetv1/model --infer_data=./third_party/inference_demo/int8v2/data.bin `
> 
> @luotao1 We want to fully align with your setup to reproduce the problem.
> 
> 1. Could you please confirm that you're using:
> 
> * the same command as shown above
> * the same models publicly available and downloaded with paddle
> * small dataset (`data.bin`)
> 
> 1. And that you compare the difference between v1.5.0 and v1.6.0-rc0 tags?
> 2. Could you also provide the CMake flags used for building?

* The test command is *./test_analyzer_int8_image_classification --infer_model=/home/pengjuncai/models/mobilenetv1/model --infer_data=/dev/shm/int8_full_val.bin --warmup --batch_size=1 --paddle_num_threads=1*
* We download the models from paddle.
* The dataset is int8_full_val.bin.
* We obtain the results according to v1.6.0-rc0 tags.
* The CMake flags used for building is *cmake ..  -DWITH_TESTING=ON -WITH_FLUID_ONLY=ON -DWITH_GPU=OFF -DWITH_MKL=ON -DWITH_MKLDNN=ON -DWITH_INFERENCE_API_TEST=ON -DON_INFER=ON*

**Comment by juncaipeng** [comment]
> @juncaipeng Could you help rerun the int8v2 benchmark with tag `v1.5.0` on the same server (6271) that you run the Release 1.6 benchmark ?

OK

**Comment by jczaja** [comment]
Some of further observations and further steps. I have run mobilenet v1 (tag v1.5.0 vs current develop). And There is Int8 as well as FP32 performance regression visible.

**Int8 performance regression:**
We have started an effort of fixing performance problem after locating changes that introduced performance harm. However to fully remove performance problem further refactoring is needed which
In our opinion should not be done at the moment of release 1.6 . So our plan is to revert  commit 2c32c2d
and revisit it during next release cycle.

**FP32 performance regression:**
This regression is smaller, but still can be observed It is related to introducing Multi-threading mechanics
in MKL-DNN integration . To be more precise Hashing key contain Thread ID apart from usual attributes and getting this TID & converting to string reduce mobilenet v1 fp32 performance. v1.5.0 does not have multi-threading support for MKL-DNN workloads.  To restore FP32 performance (or even make it a bit better) the only option now is to merge: https://github.com/PaddlePaddle/Paddle/pull/20241 . This PR
is having TID in key , but remove many of other attributes that were creating a hashing key. Some  details on this problem are described here(section a): https://github.com/PaddlePaddle/Paddle/pull/18758#issuecomment-515482597

**Comment by juncaipeng** [comment]
> @juncaipeng Could you help rerun the int8v2 benchmark with tag `v1.5.0` on the same server (6271) that you run the Release 1.6 benchmark ?

@bingyanghuang @luotao1 Test int8v2 benchmark of release 1.5 and 1.6 on the same 6271 server, the FP32 performance   as follows:

| Model        | Release 1.5 FP32 Throughput(images/s)  | Release 1.6 FP32 Throughput(images/s)  | Performance regression |
| :-----------:| :------------:             | :------------:            | :------------:  |
| GoogleNet    |    32.54                   |    32.51                  |   0.09%         |
| MobileNet-V1 |    78.14                   |   73.01                  |       **6.50%**     |
| MobileNet-V2 |    90.44                   |   90.68                  |   -0.27%         |
| ResNet-101   |     7.17                   |    7.15                  |   0.00%          |
| ResNet-50    |    13.26                   |    13.24                  |   0.15%          |
| VGG16        |     3.47                   |    3.48                  |   -0.29%         |
| VGG19        |    2.81                  |        2.80          |       0.36%      |

**Comment by jczaja** [comment]
Where we are:

#20241 - This is fix to FP32 performance that also improve INT8 performance.
#20651 - This is PR improving INT8 performance. 

It is expected that together:  #20241 and #20651 will restore performance

To test if fp32 regression is gone please test #20241 

To test if int8 regression is gone please test both #20241 and #20651 merged.

**Comment by bingyanghuang** [comment]
> Where we are:
> 
> #20241 - This is fix to FP32 performance that also improve INT8 performance.
> #20651 - This is PR improving INT8 performance.
> 
> It is expected that together: #20241 and #20651 will restore performance
> 
> To test if fp32 regression is gone please test #20241
> 
> To test if int8 regression is gone please test both #20241 and #20651 merged.

@Sand3r- @lidanqing-intel @jczaja Please firstly tested on our server and posted the benchmark here.

**Comment by bingyanghuang** [comment]
@jczaja @Sand3r-  I simply tested these several PRs on Xeon 6248 with Mobilenet- v1 and got the following benchmark:
![image](https://user-images.githubusercontent.com/33643817/66978627-43f3ca80-f0dd-11e9-8d96-84cb11aa2b5d.png)

It seems that FP32 regression has been fixed, but INT8 regression is still not totally fixed.

**Comment by luotao1** [comment]
@bingyanghuang Does these fixes affect the QAT performance?

**Comment by bingyanghuang** [comment]
> @bingyanghuang Does these fixes affect the QAT performance?

I think it will increase the QAT' s performance. Because they are running with the same conv INT8 kernel. I will update the above table with QAT data.

**Comment by bingyanghuang** [comment]
> @bingyanghuang Does these fixes affect the QAT performance?

![image](https://user-images.githubusercontent.com/33643817/66989826-ac4fa580-f0f7-11e9-91b9-8c57c3b12db4.png)

QAT is running with Python, that's reason why the absolute value has big difference on small model, besides, QAT FP32 performance is running with native FP32 model.

**Comment by juncaipeng** [comment]
We run benchmark of Release 1.6 + jacek pr, and the FP32 performance of INT8 v2 (post-training quantization) as follows:

> Throughput on Intel(R) Xeon(R) Gold 6271 (batch size 1 on single core)

| Model        | Release1.5 FP32   | Release 1.6 FP32   | Release 1.6 + jacek pr FP32   |
| :-----------:| :------------: | :------------: | :------------:  |
| GoogleNet    |    32.54 | 32.51 | 32.26 |     
| MobileNet-V1 |    78.14 | 73.01 | 75.90 |
| MobileNet-V2 |    90.44 | 90.68 | 90.43 |
| ResNet-101   |    7.17  |  7.15   |   7.17   |
| ResNet-50    |    13.26   | 13.24 | 13.25 |
| VGG16        |     3.47   |   3.48      |   3.46   |
| VGG19        |     2.81  |     2.80    |   2.81    |

**Comment by jczaja** [comment]
Notes from today,

Two PRs of ours (revert + changes on key strings) did not restore fully int8 mobilenetv1 performance.
There is  still minor performance overhead of conv int8 mkldnn integration that we are trying to trace down that impacts mobilenetv1 (~3 %). Partially this is a cost of introduced Multi-threading and a bit bigger functionality ( more activations supported in a fusing).

**Comment by bingyanghuang** [comment]
Quick benchmark on **Xeon 6271** :


Xeon 6271 | release/1.5 |   | release/1.6 |   | Diff |  
-- | -- | -- | -- | -- | -- | --
  | FP32 | INT8 | FP32 | INT8 | FP32 | INT8
Mobilenet-v1 | 78.9237 | 226.5533 | 74.2563 | 218.7752 | 5.91% | 3.43%



@Sand3r- @lidanqing-intel @jczaja

**Comment by bingyanghuang** [comment]
**TODO list:** 
- [x] Benchmark data for int8v2 with **tag v. 1.5.0** on Xeon 6271

- [x] Benchmark data for int8v2 with **release/1.6** on Xeon 6271

- [x] QAT benchmark on Xeon 6248 for accuracy

- [ ] QAT benchmark on Xeon 6271 for performance

- [x] Update the benchmark data once it's got with your build command and test env

**Comment by Sand3r-** [comment]
Xeon 6271 | v1.0.5 |   | release/1.6 |   | Diff |  
-- | -- | -- | -- | -- | -- | --
  | FP32 | INT8 | FP32 | INT8 | FP32 | INT8
Mobilenet-v1 |  |  | 78.6017 | 219.4643 |  |  
Mobilenet-v2 | 84.5083 | 192.5478 | 89.5796 | 192.8260 | -5.0713 | -0.2782
Googlenet | 31.2109 | 65.9719 | 32.6072 | 66.9066 | -1.3963 | -0.9347
Resnet50 | 13.2794 | 48.0582 | 13.3320 | 49.2027 | -0.0526 | -1.1445
Resnet101 | 7.1385 | 26.0120 | 7.1814 | 26.6005 | -0.0429 | -0.5885
VGG16 | 3.4941 | 10.5862 | 3.4985 | 10.2672 | -0.0044 | 0.319
VGG19 | 2.8490 | 9.0896 | 2.8570 | 8.8461 | -0.008 | 0.2435

QAT Accuracy on 6248:

| Model       | Fake-QAT FP32 top-1 | Optimized QAT INT8 top-1 | top-1 diff | Fake-QAT FP32 top-5 | Optimized QAT INT8 top-5 | top-5 diff |
|-------------|---------------------|--------------------------|------------|---------------------|--------------------------|------------|
| Mobilenetv1 | 0.7072              | 0.7078                   | -0.0006    | 0.8947              | 0.8939                   | 0.0008     |
| Mobilenetv2 | 0.7207              | 0.7217                   | -0.001     | 0.9065              | 0.9063                   | 0.0002     |
| Resnet50    | 0.7662              | 0.7653                   | 0.009      | 0.9301              | 0.9298                   | 0.0003     |
| Resnet101   | 0.7786              | 0.7759                   | 0.0027     | 0.9354              | 0.9354                   | 0          |
| VGG16       | 0.7174              | 0.7175                   | -0.0001    | 0.8996              | 0.8973                   | 0.0023     |
| VGG19       |                     |                          |            |                     |                          |            |

**Comment by lidanqing-intel** [comment]
We used git bisect and figured out critical commits that caused performance changes.

| mobilenetv1 Perf | release 1.5 | 1 commit before 84bb45c054e34f53c290b63d1defd76ac5ab2f94 |    84bb45c054e34f53c290b63d1defd76ac5ab2f94 | 1 commit before 0d8e6c9b8b510b4ed6827350557cdb6712b5e73e  |      0d8e6c9b8b510b4ed6827350557cdb6712b5e73e         | 1 commit before 9ecd8ee789b811e69e773a45e8258cb13e6cd8f8| 9ecd8ee789b811e69e773a45e8258cb13e6cd8f8|
|:-------:|:-------------:|:-------------:|:-----:|:----:|:----:|:----:|:----:|
| INT8 | 321.29  | 323.41 | 171.99 | 173.46 | 152.88 |152.60 | 273.96|
| fp32|  102.32 | - | - | - | - | -| 101.49|

To improve INT8 performance, we may investigate into  84bb45c054e34f53c290b63d1defd76ac5ab2f94  (-150FPS) and 0d8e6c9b8b510b4ed6827350557cdb6712b5e73e  (-20FPS)

**Comment by juncaipeng** [comment]
Release1.6 Benchmark, 2019/10/20

>**Post-training Performance on Intel(R) Xeon(R) Gold 6271**

| Model        | FP32 Throughput(images/s)  | INT8 Throughput(images/s) | 
| :-----------:| :------------:             | :------------:            | 
| GoogleNet    |    32.7627                 |   67.4343                 |   
| MobileNet-V1 |    73.9635                 |   218.8210                |  
| MobileNet-V2 |    87.9406                 |   193.7018                |   
| ResNet-101   |    7.1739                  |   26.3674                 |   
| ResNet-50    |    13.2622                 |   48.7166                 | 
| VGG16        |    3.4735                  |   10.0958                 | 
| VGG19        |    2.8167                  |   8.6842                  |  

>**QAT2 Python Performance on Intel(R) Xeon(R) Gold 6271**

| Model        | Fake QAT Throughput(images/s)  | INT8 Throughput(images/s) |
| :-----------:| :------------:             | :------------:            |
| MobileNet-V1 |    12.86                   |   118.05                  |  
| MobileNet-V2 |    9.76                    |   85.89                   |  
| ResNet101    |    2.55                    |   19.40                   |  
| ResNet50     |    4.39                    |   35.78                   |  
| VGG16        |    2.26                    |   9.89                    | 
| VGG19        |    1.96                    |   8.41                    |

**Comment by jczaja** [comment]
Further reduction of int8 perf regression can be achieved with #20753 .

As for FP32 I was not able to get reproduction on 6248 as well as 6271.

**Comment by juncaipeng** [comment]
**INT8V2 Performance on the new 6271**

>**Release1.6 INT8V2 Throughput on Intel(R) Xeon(R) Gold 6271 (batch size 1 on single core)**

| Model        | FP32 Throughput(images/s)  | INT8 Throughput(images/s) | 
| :----------: | :-------------: | :------------:  | 
| MobileNet-V1 |  77.60         |  227.66         |   
| MobileNet-V2 |  90.13         |  196.66         |  
| GoogleNet |  31.25         |  67.19         |  
| ResNet50 |  13.40         |  49.51         |  
| ResNet-101   |    7.24                 |      26.79             |   

>**Tag1.5.0 INT8V2 Throughput on Intel(R) Xeon(R) Gold 6271 (batch size 1 on single core)**

| Model        | FP32 Throughput(images/s)  | INT8 Throughput(images/s) | 
| :----------: | :-------------: | :------------:  | 
| MobileNet-V1 |  76.75         |           |    
| MobileNet-V2 |  88.43         |           |  
| GoogleNet |  31.54         |          |  
| ResNet50 |  13.39         |          |  
| ResNet-101   |    7.23                 |                  | 

For tag1.5.0, the program has bug in the new 6271.

**INT8V2 Performance on the old 6271**

>**Release1.6 INT8V2 Throughput on Intel(R) Xeon(R) Gold 6271 (batch size 1 on single core)**

| Model        | FP32 Throughput(images/s)  | INT8 Throughput(images/s) | 
| :----------: | :-------------: | :------------:  | 
| MobileNet-V1 |  84.26         |  239.89         |   
| MobileNet-V2 |  94.13         | 213.17         |  
| GoogleNet |  34.76         |  70.47         |  
| ResNet50 |  13.88         |  51.51         |

**Comment by bingyanghuang** [comment]
We can close this issue since performance regression problem has been fixed on Release 1.6.1 .
