### ISSUE TITLE
RNN roadmap for refactoring

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/Paddle#4561]
RNN is a big concept to support in our refactoring.
Based on the current support of our framework, it is better to implement RNNs in following stages:

- [x] `recurrent_op`, an RNN operator that takes a tensor as input
- [x] `dynamic_recurrent_op`, an RNN that takes variable-length sequences as input, and output sequences as output
    - should replace the `recurrent_op`
- [ ] built-in `beam search`, that will be a method in `dynamic_recurrent_op` and make the `dynamic_recurrent_op` an equivalent of the old `RecurrentGradientMachine`.
- [ ] dynamic RNN based on `while_loop` and some other conditional operators, after we support this, the infrastructure might apply to some other dynamic models such as Tree-LSTM and so on.
- [ ] dynamic beam search, that is a beam search built on `while_loop` and other conditional operations.

# Milestones

- [ ] support neural machine translation model
    - `dynamic_recurrent_op` with a built-in beam search module should be ready at that point.
- [ ] a text classification model with dynamic RNNs, the operators not limited to the following ones should be ready
    - `pd.while_loop`
    - `pd.equals`
    - `pd.TensorArray`
    - `pd.less_than`
- [ ] machine translation model based on **dynamic beam search** (maybe wrapped as `generator`)
    - that needs more dynamic operators ready

**Comment by wangkuiyi** [comment]
Should we add a final milestone as beam search using WhileOp and IfElseOp?

**Comment by Superjom** [comment]
yes, the dynamic beam search should be the final challenge, I will add it.

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
