### ISSUE TITLE
Optimizer Design and Implementation

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#4679]
## Goal

Implement `Optimizer` with new CompileTime & RunTime architecture.

## optimizer used in book chapter:
1. Momentum. 
01.fit-a-line
02.recognize_digits
03.image_classification
07.label_semantic_roles
2. AdaGrad
3. Adam
4. L2Regularization
5. ModelAverage

### Optimizer Framework
- [x] Optimizer survey @jacquesqiao (https://github.com/PaddlePaddle/Paddle/issues/3672)
- [x] optimizer Python API Design @jacquesqiao (https://github.com/PaddlePaddle/Paddle/pull/4656)
- [x] expose backward of ProgramDesc to python. @jacquesqiao (https://github.com/PaddlePaddle/Paddle/pull/4699)
- [x] improve backward @jacquesqiao (https://github.com/PaddlePaddle/Paddle/pull/4796)
- [x] create grad_var when run Backward pass @jacquesqiao (https://github.com/PaddlePaddle/Paddle/pull/4796)
- [x] Python cpp sync @jacquesqiao (https://github.com/PaddlePaddle/Paddle/issues/4786)
- [x] implement the interface of optimizer. @jacquesqiao (https://github.com/PaddlePaddle/Paddle/pull/4734)

###  Optimize operators:
   - [x] Adagrad @kexinzhao (https://github.com/PaddlePaddle/Paddle/pull/4558)
   - [x] Decayed Adagrad @kexinzhao (https://github.com/PaddlePaddle/Paddle/pull/4645)
   - [x] Adadelta @abhinavarora (https://github.com/PaddlePaddle/Paddle/pull/4576)
   - [x] Adamax @abhinavarora (https://github.com/PaddlePaddle/Paddle/pull/4538)
   - [x] AdamOp @abhinavarora (https://github.com/PaddlePaddle/Paddle/pull/4733)

### Python Optimizer Wrapper
   - [x] Fix initialization of tensors (https://github.com/PaddlePaddle/Paddle/issues/4975). Dependent on https://github.com/PaddlePaddle/Paddle/pull/4852  @jacquesqiao https://github.com/PaddlePaddle/Paddle/pull/5275
   - [x]  Momentum Op Wrapper @abhinavarora (https://github.com/PaddlePaddle/Paddle/issues/4898)
   - [x] Adam Op Wrapper @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/5021
   - [x] Adagrad Op Wrapper @kexinzhao (https://github.com/PaddlePaddle/Paddle/issues/4916)
   - [x] Decayed Adagrad Op Wrapper @kexinzhao (https://github.com/PaddlePaddle/Paddle/issues/4993)
   - [x]  Adamax Op Wrapper @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/5061
   - [x] Support Nesterov momentum in momentum wrapper @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/5055
   - [x] Increment global step if provided @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/5097

### Related ToDos
   - [x] Implement the increment op for global step @abhinavarora(https://github.com/PaddlePaddle/Paddle/issues/4912)
   - [x]  Fix Adam Op @abhinavarora (https://github.com/PaddlePaddle/Paddle/issues/4909)
   - [x]  Fix Adamax Op @abhinavarora (https://github.com/PaddlePaddle/Paddle/issues/4920)

**Comment by reyoung** [comment]
@jacquesqiao should this issue closed?
