### ISSUE TITLE
Regularization Design for PaddlePaddle

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Paddle#5054]
This issue is used to track the different tasks needed for supporting regularization in PaddlePaddle

**Comment by abhinavarora** [comment]
### Goal
Implement Regularization with new compile time and runtime Paddle architecture

### Tasks
- [x] Regularization Survey @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/4869
- [x] Design Doc for Regularization @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/4869
- [ ] Implement C++ operator for L2 norm for L2 regularization @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/5030
- [ ] Implement C++ operator for L1 norm for L1 regularization @abhinavarora
