### ISSUE TITLE
赛题六：飞桨框架 C++ 文档抽取与展示 Tracking Issue

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/Paddle#54075]
# 赛题简介
飞桨深度学习框架为用户提供了 Python API 官方文档，便于用户查阅 API 对应的源代码、参数、返回值等。[赛题六：飞桨框架 C++ 文档抽取与展示](https://github.com/PaddlePaddle/Paddle/issues/53172)，要求为飞桨框架自动抽取和展示 C++ 文档，并上线至飞桨官网。

更多信息参考 [中国软件开源创新大赛：飞桨框架任务挑战赛](https://github.com/PaddlePaddle/Paddle/issues/53172)

# 任务进展
## rfc提交
- [x] https://github.com/PaddlePaddle/community/pull/529
## 基础工作
- [x] 解析编译后代码，抽取API名称、返回值信息，并构造rst文档
- [x] 解析注释，将doxygen解析为API说明、参数说明、返回值说明信息，并构造rst文档
- [x]  Overview页面生成和构造工作
- [x] 中英文文档生成，同步生成rst文档
- [x] Python API映射，根据compat.h文件，映射API到Python API，并添加对应说明
## 前端协作上线
- [x] 工作核验与确认。关于工作评审与修改进展，见 https://github.com/Liyulingyue/DocsCodes/issues/5
- [x] 文档生成代码提交与合入 https://github.com/PaddlePaddle/docs/pull/5900
- [x] readthedocs.io上线 https://paddlecppapidocs.readthedocs.io/en/latest/index.html#
## CI补充
- [x] 在paddle测增加CI，禁止无注释的PADDLE_API添加 https://github.com/PaddlePaddle/Paddle/pull/53956

## 进阶（可作为结项后工作进行）
- Python API映射工作，设置脚本检索是否存在API映射
- URL映射工作，尝试给API添加源代码链接

**Comment by luotao1** [comment]
和 @jzhang533 @jiahy0825 讨论后：
1. **本赛题可以认为基本完成**
2. 但有几个注意点请 @Liyulingyue @gouzil 知晓：
- 软件开源创新大赛是需要答辩的，赛题完成不等于最终答辩名次。比赛前，会组织所有选手预答辩。
- 本赛题有特殊性，需要等待飞桨官网上线（时间不确定），因此
   - @sunzhongkai588 会提PRD给官网前后端，但由于 readthedocs 展示页面和官网格式可能有 diff 的，后续如果官网有适配要求，需要选手帮忙响应下
   -  readthedocs 展示页面可以自行优化美观，如果官网无法上线，可以使用 readthedocs 网站。
