### ISSUE TITLE
赛题七：实现飞桨框架动态图反向图的可视化 Tracking Issue

### ISSUE THREAD

**Issue by qiuwenbogdut** [PaddlePaddle/Paddle#54347]
# 赛题简介
[赛题七](https://github.com/PaddlePaddle/Paddle/issues/53172#paddlepaddle07): 飞桨深度学习框架提供了动态图编程的模式来开发深度学习模型（方便开发与调试），但动态图的反向图调试能力仍存在不足。
本赛题，要求为飞桨动态图框架添加反向节点在 Python 端的访问机制。并在该机制基础上，为飞桨框架扩展反向图可视化能力。

赛题要求：
* 学习动态图框架，有能力为动态图扩展接口。
* 学习 PyTorchViz 使用方法和原理。
* 为飞桨动态图框架扩展 Python 端访问反向节点的能力，包括不限于 grad_fn、next_functions等
* 参考 PyTorchViz 实现飞桨动态图反向图的可视化
* 丰富反向图信息：如 Tensor 名、Tensor dtype、Tensor shape、前向堆栈等

# 任务进展
## rfc提交
 https://github.com/PaddlePaddle/community/pull/535

## 工作拆分
 模块一: 开发grad_fn、next_functions两个python API接口 #54838 

- [x]  grad_node 反向图节点数据类型暴露给python端
- [x]  tenmsor属性grad_fn暴露给python端
- [x]  grad_node的属性next_function的实现
- [x]  next_function暴露给python端
- [ ] 优化

模块二: 基于步骤一的接口进行反向图可视化 https://github.com/PFCCLab/paddleviz

- [x]  获取反向图所有节点信息
- [x]  将反向图的节点信息构建一个有向图
- [x]  基于这个图使用工具****graphviz**** 进行可视化显示

模块三: 构架测试脚本进行有效性验证

- [x]  功能测试

**Comment by Fancy-hjyp** [comment]
认领模块二`反向图可视化`功能的开发

**Comment by luotao1** [comment]
本赛题：实现飞桨框架动态图反向图的可视化，已完成，感谢 @qiuwenbogdut @Tomoko-hjf !
后续可以考虑在现有图的基础上，加上输入输出Tensor的information，难度会大一些。
