### ISSUE TITLE
refine chinese document

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#546]
- [ ] ./algorithm/rnn/hierarchical-layer.md
- [ ] ./algorithm/rnn/hierarchical-rnn.md #508 
- [ ] ./algorithm/rnn/rnn-tutorial.md
- [ ] ./build/docker/build_docker_image.rst
- [ ] ./build_and_install/cmake/compile_options.rst #531
- [ ] ./build_and_install/cmake/index.rst
- [ ] ./build_and_install/cmake/install_deps.rst #533
- [ ] ./build_and_install/cmake/make_and_install.rst #533
- [ ] ./build_and_install/index.rst
- [ ] ./build_and_install/install/docker_install.rst #533
- [ ] ./build_and_install/install/ubuntu_install.rst
- [ ] ./cluster/index.rst
- [ ] ./concepts/nn.rst
- [ ] ./concepts/program_concepts.rst
- [x] ./concepts/use_concepts.rst #532
- [ ] ./demo/index.rst
- [ ] ./demo/quick_start/index.md #538
- [ ] ./faq/index.rst
- [ ] ./howto/how_to_write_docs/index.rst #527 
- [ ] ./index.rst
- [ ] ./introduction/index.md
- [ ] ./ui/cmd/dump_config.rst
- [ ] ./ui/cmd/index.rst
- [ ] ./ui/cmd/make_diagram.rst
- [ ] ./ui/cmd/merge_model.rst
- [ ] ./ui/cmd/paddle_pserver.rst
- [ ] ./ui/cmd/paddle_train.rst
- [ ] ./ui/cmd/paddle_version.rst
- [ ] ./ui/data_provider/index.rst
- [ ] ./ui/data_provider/pydataprovider2.rst
- [ ] ./ui/data_provider/write_new_dataprovider.rst
- [ ] ./ui/index.rst
- [ ] ./ui/predict/swig_py_paddle.rst
