### ISSUE TITLE
赛题五：将 xdoctest 引入到飞桨框架工作流中 Tracking Issue

### ISSUE THREAD

**Issue by megemini** [PaddlePaddle/Paddle#54705]
### 赛题五：将 xdoctest 引入到飞桨框架工作流中

xdoctest 是一个示例代码自动执行和检查工具，可以自动执行 Python docstring 中的示例代码，并对示例代码输出进行检查。
本赛题，要求将 xdoctest 引入到飞桨框架的工作流中，利用 xdoctest 来自动检查示例代码运行正确，且输出结果匹配，以确保示例代码输出的一致性，进一步提高飞桨框架示例代码的质量。

更多信息参考 [中国软件开源创新大赛：飞桨框架任务挑战赛](https://github.com/PaddlePaddle/Paddle/issues/53172#top)

### RFC

* [x] https://github.com/PaddlePaddle/community/pull/547

### 第一阶段

* [x] https://github.com/PaddlePaddle/docs/pull/5941
* [x] https://github.com/PaddlePaddle/docs/pull/5962
* [x] https://github.com/PaddlePaddle/Paddle/pull/55295
### 第二阶段

* [x] https://github.com/PaddlePaddle/docs/pull/6096
* [x] https://github.com/PaddlePaddle/Paddle/pull/56573
* [x] https://github.com/PaddlePaddle/docs/pull/6129

### 第三阶段

*  <del> 代码检查移交 收尾 </del> 此任务分解为：第二阶段最后一个任务，与第三阶段的两个收尾任务
* [x] 清理遗留代码
  - #57670
* [x] 清理无 reason 的 skip 示例
* [x] 清理 fluid 代码 
  *Update `20230922`*
  - commit `579103d91e`, 未发现遗留使用 fluid 的示例
  - https://github.com/PaddlePaddle/Paddle/pull/57421 已 merge，后续会检查此类示例

## 批量任务

* [x] https://github.com/PaddlePaddle/docs/issues/5957
* [x] https://github.com/PaddlePaddle/Paddle/issues/55629

## 其他任务

* [ ] 中英文 API 文档特性更新（官网 copy 功能）

@SigureMo @luotao1 @jzhang533 @sunzhongkai588

请悉知～ ：）

**Comment by luotao1** [comment]
中英文 API 文档特性更新（官网 copy 功能）后续 @sunzhongkai588 孙师傅会跟进😄
