### ISSUE TITLE
Remaining tasks for fluid

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#5813]
We complete the most jobs for fluid release, but still there are several tasks remains.
[tasks.dot.txt](https://github.com/PaddlePaddle/Paddle/files/1494524/tasks.dot.txt)
![tasks](https://user-images.githubusercontent.com/728699/33108828-308705de-cf79-11e7-9235-274b956486a3.png)

There are two colors in each block, aquamarine and white. The tasks in the white blocks is under developing right now. We need help to complete the tasks in the aquamarine blocks.

NOTE: The tasks and graph of dependencies could be flux.

There are five major parts of tasks:

1. Polish our Python API. Make the high level Python API as same as our V2 API.
  - [x] Transform training ProgramDesc to testing #5733 #5734 
  - [x] test while training #5814 #5734 
  - [x] Basic Performance tunning
     * [x] Performance tunning guide documentation #5895 
  - [x] Training data IO API desgin
     * [x] Executor can use numpy tensor as its input/output #5620 
     * [x] Executor can use numpy list for LoD i/o
  - [x] Parameter Attribute Design and initializers #5819
  - [x] Evaluator design
    * #5825
  - [x] Enhancement for fluid API
    * [x] Restore param info when Program.clone() #5871
    * [x] Unify the fluid imports into `paddle.v2.fluid` #5876 
    * [x] A Better way to switch default program #5929
  - [x] ~~Paddle V2 Proxy Layer~~ In next release.
  - [x] Make API function parameter name consistantly
  - [x] Polish C++ operators
    * Operator should support many data types, not only float.  #5827
  - [x] Machine Translation Demo
    - [x] neural machine translation training https://github.com/PaddlePaddle/Paddle/issues/6400
    - [x] predicting 
2. Complete our last two chapter in our book.
  - [x] 07/Label semantic roles #5798
3. Synchronize our training accuracy with previous Paddle and other frameworks.
   * We train same data with same configuration and same initialization. We should make `fluid` produce the exactly same result with previouse Paddle or other frameworks. `Exactly` means the epsilon should be less than 1e-4.
4. Polish Op & Layer documentation.
   * The most crucial task is generate Op & Layers documentation HTML files, and publish it in our staging sever.
5. Releasing new docker images & pip packages
   * Also run the regression tests.

**Comment by reyoung** [comment]
Done.
