### ISSUE TITLE
Python 各版本可以退场的代码

### ISSUE THREAD

**Issue by SigureMo** [PaddlePaddle/Paddle#59685]
我们在开发过程中难免会有一些版本兼容代码，但这些代码应当在旧版本退场时进行清理，这里记录一些我个人阅读代码、开发过程中所了解到的一些版本兼容代码，欢迎大家补充

<details>
<summary>已退场版本</summary>

## Python 3.7

- [x] AST 动转静 origin_info 单测相关适配逻辑 #27201（#59569 已移除）

## Python 3.8

- [x] copysign 宏，3.9 及以上版本可以安全删除 #50387 （#72856 已清理）
- [x] eval_frame 中的 3.8 从 CPython 中 copy 出来的 internal 代码 https://github.com/PaddlePaddle/Paddle/blob/9985598affbb3f834fdd6d1d0afbaeefcd2b45d3/paddle/fluid/pybind/eval_frame.h#L26 （#57662 已清理﻿）
- [x] eval_frame 3.8 相关适配逻辑（#72868 已清理）
- [x] SOT 3.9 退场的字节码（PaddlePaddle/PaddleSOT#118）（#72855 已清理）
- [x] 第三方库 astor，AST 动转静只使用了 unparse 的功能，但这可以使用 Python 3.9 自带的更稳定的 `ast.unparse` 取代，berkerpeksag/astor#204 也有相关讨论（#72870 已清理）
- [x] #65377 因为 3.8 `Literal` 反编译回字符串时出 bug 了，因此加了调整的逻辑，3.9 可以安全清理（#72873 已清理）
- [x] 动转静单测 `check_approval.py` 里为 3.8 加的 unparse 逻辑 #72560 https://github.com/PaddlePaddle/Paddle/blob/7d0dee330252dc92115d708734a89b10ef5249da/test/dygraph_to_static/check_approval.py#L55-L82
- [x] 文档[《Python 类型提示标注规范》](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/style_guide_and_references/type_annotations_specification_cn.html)中 Python 3.8 相关内容（PaddlePaddle/docs#7307 已更新）
- [x] Ruff B005 引入并修复相关 bug（因为 Python 3.9 `removesuffix` 和 `removeprefix` 已经 ready），见 https://github.com/PaddlePaddle/Paddle/pull/52103#issuecomment-1482449812 （#72896 已清理）
- [x] Python 3.9 可以使用 dict union[^1]，因此可以用 ast-grep 搜 `{**$A, **$B}` 搜索并替换下，~~SOT 里的 `union_free_vars` 也没有存在的必要了，相关地方直接用 `A | B | C` 即可~~（后者先不要修改了，`union_free_vars` 语义会清晰些，而且在 C++ guard 里并不会存在，在退掉 py guard 时自然就清理掉了）（#72891 已修改）

## Python 3.9

- [x] SOT `co_lnotab` 生成逻辑，3.10 及之后会使用 `co_linetable` https://github.com/PaddlePaddle/Paddle/blob/a3ed849a3cc9248a50aaa521eb62c1adf91684fb/python/paddle/jit/sot/opcode_translator/executor/pycode_generator.py#L248 （#79290 已清理）

</details>

## Python 3.10

- [ ] SOT `co_linetable` 3.10 生成逻辑 https://github.com/PaddlePaddle/Paddle/blob/a3ed849a3cc9248a50aaa521eb62c1adf91684fb/python/paddle/jit/sot/opcode_translator/executor/pycode_generator.py#L273
- [ ] SOT 中各种 3.11 与之前的适配逻辑，主要包含字节码模拟执行和字节码生成逻辑，字节码可参考 #69134
- [ ] `eval_frame` 中各种 3.11 与之前的适配逻辑
- [ ] 3.10- 专有的异常处理逻辑

## Python 3.11

- [ ] SOT `PRECALL` 字节码相关逻辑，3.12 中该字节码已经被移除
- [ ] SOT 其余字节码（3.12 也删了不少字节码），可参考 #69134 清理

## Python 3.12

- [ ] SOT `NULL fn` 布局的处理，Python 3.13 中全部使用 `fn NULL` 布局，包括 `NullVariable` 的 `__call__`、`gen_load_null_variable` 等操作应该也不具备实际意义，均可清理

## Python 3.13

- [ ] PEP 563 `from __future__ import annotations`[^2]，Python 3.14 中已经被 PEP 649[^3] 所取代
- [ ] `test/sot/test_26_t_string.py` 奇怪的写法可以修改下了，用正常的写法即可

[^1]: [PEP 584 – Add Union Operators To dict](https://peps.python.org/pep-0584/)
[^2]: [PEP 563 – Postponed Evaluation of Annotations](https://peps.python.org/pep-0563/)
[^3]: [PEP 649 – Deferred Evaluation Of Annotations Using Descriptors](https://peps.python.org/pep-0649/)
