### ISSUE TITLE
【Hackathon 6th Fundable Projects No.4】Paddle 框架旧执行器功能退场 Tracking Issue

### ISSUE THREAD

**Issue by ccsuzzh** [PaddlePaddle/Paddle#63510]
### 一、BackGround

飞桨 Paddle 自 2.0 版本以来，进行了多个重大机制改造。包括：高可复用算子库 PHI、全新的动态图体系、全新的静态图执行引擎等。随着新机制的发布使用，旧机制和功能代码需要进行退场和移除，保持架构清晰和代码库的条理性，为内外部开发者提供更好的二次开发环境。这就包括了 Operators 算子库的清理、旧动态图机制代码的清理、旧静态图执行引擎的清理。

2.0 版本后静态图虽然是非默认形态，但以 Interpreter 为中心的内核执行器正式取代了旧的 ParallelExecutor 执行器，提供了更优调度策略的新执行器。因此飞桨考虑虑将此系列旧执行器进行退场处理。

详细见：[Paddle 框架旧执行器功能退场](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/%E3%80%90Hackathon%206th%E3%80%91FundableProject%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#%E5%9B%9Bpaddle-%E6%A1%86%E6%9E%B6%E6%97%A7%E6%89%A7%E8%A1%8C%E5%99%A8%E5%8A%9F%E8%83%BD%E9%80%80%E5%9C%BA)

### 二、Task

任务描述详细见RFC：
- https://github.com/PaddlePaddle/community/pull/853

|序号|任务描述 |认领人/状态/PR号|
| -- | -- | -- |
| 1 | 移除旧执行器单元测试✅ | @ccsuzzh <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#63543](https://github.com/PaddlePaddle/Paddle/pull/63543)<br> | 
| 2 | 完成`ParallelExecutor`编译模块迁移✅ | @ccsuzzh <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#63758](https://github.com/PaddlePaddle/Paddle/pull/63758) [#6782](https://github.com/PaddlePaddle/docs/pull/6782)<br> | 
| 3 | 移除`ExecutionStrategy` ✅ | @ccsuzzh <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#63132](https://github.com/PaddlePaddle/Paddle/pull/63132) [#65077](https://github.com/PaddlePaddle/Paddle/pull/65077) [#6694](https://github.com/PaddlePaddle/docs/pull/6694)<br> | 
| 4 | CINN 中旧执行器代码退场✅ | @ccsuzzh <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#63473](https://github.com/PaddlePaddle/Paddle/pull/63473)<br> | 
| 5 | 移除`ParallelExecutor`执行器相关代码 | @ccsuzzh <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#64822](https://github.com/PaddlePaddle/Paddle/pull/64822) [#64818](https://github.com/PaddlePaddle/Paddle/pull/64818) [#65189](https://github.com/PaddlePaddle/Paddle/pull/65189) [#6694](https://github.com/PaddlePaddle/docs/pull/6694) [#65340](https://github.com/PaddlePaddle/Paddle/pull/65340) [#65462](https://github.com/PaddlePaddle/Paddle/pull/65462) [#65894](https://github.com/PaddlePaddle/Paddle/pull/65894) [#66293](https://github.com/PaddlePaddle/Paddle/pull/66293)<br> | 
| 6 | 移除`AsyncExecutor`执行器相关代码✅ | @ccsuzzh <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#63923](https://github.com/PaddlePaddle/Paddle/pull/63923)<br> | 

#### 任务一：移除旧执行器单元测试✅（整体进展：27/27）

|处理方式|单测文件统计|PR链接
| -- | -- | -- |
部分删除|cinn_launch_context_test.cc✅|#63470
直接删除|share_varinfo_into_cinn_pass_test.cc✅|#63470
部分删除|test_reference_count_pass_last_lived_ops.cc✅|#63758
直接删除|parallel_executor_test_base.py✅| #63543
部分删除|seresnext_net.py✅|#63543
直接删除|seresnext_test_base.py✅|#63543
直接删除|test_fuse_all_reduce_pass.py✅|#63543
部分删除|test_fuse_elewise_add_act_pass.py✅|#63543
直接删除|test_fuse_optimizer_pass.py✅|#63543
直接删除|test_fuse_relu_depthwise_conv_pass.py✅|#63543
直接删除|test_ir_inplace_pass.py✅|#63543
直接删除|test_ir_memory_optimize_pass.py✅|#63543
直接删除|test_ir_memory_optimize_transformer.py✅|#63543
直接删除|test_mix_precision_all_reduce_fuse.py✅|#63543
直接删除|test_parallel_executor_run_cinn.py✅|#63543
直接删除|test_parallel_executor_seresnext_base_cpu.py✅|#63543
直接删除|test_parallel_executor_seresnext_base_gpu.py✅|#63543
直接删除|test_parallel_executor_seresnext_with_fuse_all_reduce_cpu.py✅|#63543
直接删除|test_parallel_executor_seresnext_with_fuse_all_reduce_gpu.py✅|#63543
直接删除|test_parallel_executor_seresnext_with_reduce_cpu.py✅|#63543
直接删除|test_parallel_executor_seresnext_with_reduce_gpu.py✅|#63543
直接删除|test_parallel_executor_transformer_auto_growth.py✅|#63543
直接删除|test_parallel_executor_transformer.py✅|#63543
部分删除|test_program_prune_backward.py.py✅|#63543
部分删除|test_py_func_op.py✅|#63543
部分删除|test_standalone_executor.py✅|#63543
部分删除|test_weight_decay.py✅|#63758

#### 任务二：完成`ParallelExecutor`编译模块迁移✅ 

- [x] 完成`CompiledProgram`的兼容，与`ParallelExecutor`彻底解绑
  - #63758
- [x] 移除`build_strategy`中无用的属性
  - #65894 
  - #66293 
- [x] Docs仓库同步更新
  - https://github.com/PaddlePaddle/docs/pull/6782

#### 任务三：移除`ExecutionStrategy` ✅

- [x] 移除Python端`ExecutionStrategy` 
   - #63132 
- [x] 移除C++端`ExecutionStrategy` 
   - #65077
- [x] Docs仓库同步更新
  - https://github.com/PaddlePaddle/docs/pull/6631 
  - https://github.com/PaddlePaddle/docs/pull/6694

#### 任务四：CINN 中旧执行器代码退场✅

 - [x] #63470
 - [x] #63473

#### 任务五： 移除`ParallelExecutor`执行器相关代码

- [x] `ParallelExecutor` pybind代码退场
  - #64822  
- [x] `ParallelExecutor`和`SSAGraphExecutor`及其派生类代码退场
  - #64818
  - #65189
- [x] 移除OpHandle组件
  - #65340 
  - #65462
  - #65894
  - #66293
  - #66558  
 - [x] Docs仓库同步更新
   - https://github.com/PaddlePaddle/docs/pull/6694

#### 任务六： 移除`AsyncExecutor`执行器相关代码✅

- [x] `AsyncExecutor`相关代码退场
  - #63923

## 看板信息 
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
|  Fundable Projects No.4  |  6  | 6 / 6 | 100.0% |  6  | 100.0% |
#####

## 统计信息 
> 排名不分先后 @ccsuzzh (6) 
#####
