### ISSUE TITLE
VGG-16 performance comparison with TensorFlow

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#6635]
VGG-16 model has been selected as a benchmark model.
- [x] write VGG-16 model based on Fluid (#6758)
- [x] write VGG-16 model based on TensorFlow (#6759)
- [x] CPU  version  loss convergence comparison(#6944)
- [x] GPU version loss convergence comparison(#6813)
- [x] CPU version speed comparison and enhancement(#6911)
- [x] GPU version speed comparison and enhancement(#6814 )

**Comment by kuke** [comment]
One thing remaining: [the performance of VGG16 needs to be optimized](https://github.com/PaddlePaddle/Paddle/issues/6918)

**Comment by kuke** [comment]
About the memory allocation: https://github.com/PaddlePaddle/Paddle/issues/6968
