### ISSUE TITLE
book.05 recommendation systems performance comparison with V2

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#6649]
- [ ] CPU  version  loss convergence comparison (https://github.com/PaddlePaddle/Paddle/issues/7167)
- [ ] GPU version loss convergence comparison (https://github.com/PaddlePaddle/Paddle/issues/7168)
- [ ] CPU version speed comparison and enhancement (https://github.com/PaddlePaddle/Paddle/issues/7169)
- [ ] GPU version speed comparison and enhancement (https://github.com/PaddlePaddle/Paddle/issues/7170)

**Comment by typhoonzero** [comment]
Ref: https://github.com/PaddlePaddle/Paddle/pull/6601

**Comment by typhoonzero** [comment]
| pass | cost fluid | cost v2 |
| ---- | ----------| -------- | 
| 0 | 4.910392 | |
| 1 |  4.181918 | |
| 2 | 6.909574 | |
| 3 |  4.727365 | |
| 4 |  4.727350 | |
| 5 |  5.818351 | |
| 6 |  3.818373 | |
| 7 |  4.909399 | |
| 8 |  4.727339 | |
| 9 |  7.272834 | |

**Comment by dzhwinter** [comment]
The benchmark job has been done.
