### ISSUE TITLE
06.understand_sentiment performance comparison with V2

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#6650]
understand_sentiment has three implementations in Fluid, based on `cnn model`, `static_rnn`, `dynamic_rnn`. 
It has two implementations in V2. We **only need to compare the `static_rnn` one with V2**.

- [x] CPU  version  loss convergence comparison #7054 
- [x] GPU version loss convergence comparison  https://github.com/PaddlePaddle/Paddle/issues/7046
- [ ] CPU version speed comparison and enhancement #7220 
- [ ] GPU version speed comparison and enhancement #7096

**Comment by dzhwinter** [comment]
The benchmark job has been done.
