### ISSUE TITLE
book.04 word2vec  performance comparison with V2

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#6710]
- [x] CPU  version  loss convergence comparison(https://github.com/PaddlePaddle/Paddle/issues/7052)
- [x] GPU version loss convergence comparison (https://github.com/PaddlePaddle/Paddle/issues/7044)
- [x] CPU version speed comparison and enhancement (https://github.com/PaddlePaddle/Paddle/issues/7087)
- [x] GPU version speed comparison and enhancement (https://github.com/PaddlePaddle/Paddle/issues/7088)

**Comment by peterzhang2029** [comment]
**Word2vec (CPU)**

Train accuracy:

| Pass |  V2(CPU) | Fluid(CPU) |
|---------------  | ---------------  | ------------------- |
|0 | 0.176933 | 0.175965 |
|1 | 0.192791 | 0.194267 |
|2 | 0.201777 | 0.205418 |
|3 | 0.207228 | 0.210301 |
|4 | 0.210267 | 0.213032 |

Time cost (second):

| Pass |  V2(CPU) | Fluid(CPU) |
|---------------  | ---------------  | ------------------- |
|0 | 8760.865  | 20683.424 |
|1 | 8543.590 | 20202.207 |
|2 | 8548.695 | 20678.671 |
|3 | 8627.016 | 20227.047 |
|4 | 8641.707 | 20464.214 |
|avg: | 8624.375 | 20451.1126 |


**Word2vec (GPU)**

Train accuracy:

| Pass |  V2(GPU) | Fluid(GPU) |
|---------------  | ---------------  | ------------------- |
|0 | 0.176836 | 0.176102 |
|1 | 0.192027 | 0.193470 |
|2 | 0.201134 | 0.200178 |
|3 | 0.206348 | 0.207074 |
|4 | 0.209392 | 0.212089 |

Time cost (second):

| Pass |  V2(GPU) | Fluid(GPU) |
|---------------  | ---------------  | ------------------- |
|0 | 36.741  | 117.568 |
|1 | 35.636 | 119.425 |
|2 | 35.868 | 117.857 |
|3 | 35.619 | 116.161 |
|4 | 35.330 | 116.011 |
|avg: | 35.839 | 117.404 |
