### ISSUE TITLE
Refine current codes to support multi-devices 2

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#6746]
**First part:**

- [x] Implement CUDNNDeviceContext, MKLDeviceContext hierarchy.  
Use decorator design pattern is not fit our needs so well, doing other things first.
- [x] define LayoutType key #6827 #6832 
- [x] define LibraryType key #6770 #6874 
- [x] define the new OpKernelType class(four keys DataType/LayoutType/Place/LibraryType). #6769 #6879 
- [x] refine current kernel register mechanism
- [x] refine CUDNN related operators, change them from operators to kernels https://github.com/PaddlePaddle/Paddle/pull/6660
- [x] Remove `CUDNNPlace` and `MKLDNNPlace` follow new design
- [x] rename GPUPlace to CUDAPlace
- [x] add multikernel python test support

**Second part:**
- [x] refine Tensor implementation, add a `layout` attribute #6765  https://github.com/PaddlePaddle/Paddle/pull/6955
- [x] refine Python interface and some data operators to set `layout`.
- [x] share Tensor layout in most operators

**Third part:**
- [x] DataTransform function interface.
- [x] DataTransformFn register mechanism #6823
- [x] kernel hint and GetExpectedKernelType #6883
- [x] memory switch mechanism #6989 #6991 
- [x] refine memory switch mechanism in local scope #7057 #7058 
- [ ] implement some basic DataTransformFn
   - [ ] CPU <---> CUDA #7050
   - [x] layout transform, like mkldnn
   - [ ] change batch norm to use new transform method
- [ ] add method to judge which inputs should be transformed [refs](https://github.com/PaddlePaddle/Paddle/pull/6991#discussion_r158632361)
- [x] Python interface setting kernel hint
- [x]  helper function of getting appropriate DeviceContext #7065 #7066
- [ ] Add a mnist example that switch kernel
- [ ] Refine current CRF operator

**Comment by dzhwinter** [comment]
This issue related with https://github.com/PaddlePaddle/Paddle/issues/6507
