### ISSUE TITLE
06.understand_sentiment performance comparison with TensorFlow

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#7031]
- [ ] Implement stacked dynamic lstm for fluid. https://github.com/dzhwinter/benchmark/issues/32
- [ ] Implement stacked dynamic lstm for tf. https://github.com/dzhwinter/benchmark/issues/33
- [ ] Speed comparison on CPU. https://github.com/PaddlePaddle/Paddle/issues/7033
- [ ] Speed comparison on GPU.
- [ ] Convergence comparison on CPU.
- [ ] Convergence comparison on GPU.
