### ISSUE TITLE
Distributed training milestones

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#7256]
This issue tracks the overall program, more detailed issues are in  https://github.com/PaddlePaddle/Paddle/projects/30

- [x] Optimizer support sparse update @typhoonzero 
- [x] PServer Sparse Update 1/4/2018 - 1/9/2018 @Yancey1989 
- [x] send / recv multiple parameters in async 1/4/2018 - 1/9/2018 @gongweibao 
- [x] Multiple node performance tuning 1/8/2018 - 1/30/2018 @gongweibao , @typhoonzero @Yancey1989 @helinwang @putcn 
- [x] Make every chapter of book works with distributed training 1/2/2018 - 1/12/2018 @typhoonzero , @gongweibao @Yancey1989 @helinwang @putcn 
- [x] Prefetch model from server 1/15/2018-1/19/2018 @Yancey1989 
- [x] Shard a single variable to different parameter servers @typhoonzero 
- [ ] Remote executor @gongweibao 
- [ ] Reader OP, iteration OP TBD

**Comment by typhoonzero** [comment]
Can we close this issue now? We may open another issue to describe future TODOs need to be done to complete dist training.

**Comment by helinwang** [comment]
Thanks! Closing.
