### ISSUE TITLE
TODO list for the ConvS2S.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#7353]
~~- [ ] prepare the dataset https://arxiv.org/abs/1605.00459.~~ *a shared task with Transformer*
~~- [ ] enhance the lookup_table operator to support the special token: padding index.  https://github.com/PaddlePaddle/Paddle/issues/7309.~~ *a shared task with Transformer*

- [x] implement a general purpose normalization operator https://github.com/PaddlePaddle/Paddle/issues/7350.  @lcy-seso
- [x] wrap the weight normalization.
    - [x] l2 normalize layer.
    - [x] wrap weight normalization.
    - [ ] serialize weight normalization for inference.
- [x] wrap the positional embedding.
- [x] wrap the dot product attention. https://github.com/PaddlePaddle/Paddle/pull/7602
- [x] wrap GLU unit. https://github.com/PaddlePaddle/Paddle/pull/7525
- [x] wrap deep convolution encoding and decoding block with attention.
- [x] build the entire model.
- [x] enhance the documentation of operators used in ConvS2S.
- [ ] add beam search for ConvS2S.
- [ ] merge the entire model into the [models](https://github.com/PaddlePaddle/models) repo (actually can merge the work part by part).
- [x] clip by norm
