### ISSUE TITLE
TODO list for RNN search.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#7357]
- [x] enhance the `reorder_lod_tensor_by_rank operator`. PR https://github.com/PaddlePaddle/Paddle/pull/7251
- [x] add the external memory (the static input in old PaddlePaddle) to `dynamicRNN`. PR https://github.com/PaddlePaddle/Paddle/pull/7434
- [x] make the RNN search model successfully run on Fluid.
    - https://github.com/dzhwinter/benchmark/blob/master/fluid/machine_translation.py
- [x] test the RNN encoder-decoder without attention (This is another test case for  `reorder_lod_tensor_by_rank operator`, so it should be tested also).
- [ ] enhance the documentation of operators used in RNN Search.
- [x] debug and unittest the beam search related operators. @jacquesqiao is working on this, related PR (WIP) https://github.com/PaddlePaddle/Paddle/pull/7340 .
  - [x] [add lod tensor ToAbsOffset test](https://github.com/PaddlePaddle/Paddle/pull/7372)
  - [x] [Topk share lod](https://github.com/PaddlePaddle/Paddle/pull/7373)
  - [x] [change data type of beam_search op](https://github.com/PaddlePaddle/Paddle/pull/7374)
  - [x] [Add get lod for debug](https://github.com/PaddlePaddle/Paddle/pull/7375)
  - [x] [nmt model with beam search](https://github.com/PaddlePaddle/Paddle/pull/7340)
- [ ] wrapper the beam search: issue https://github.com/PaddlePaddle/Paddle/issues/6900 .
- [ ] provide a more friendly Python wrapper which unifies training and generating sequences.
