### ISSUE TITLE
The TODO lists for MobileNet-SSD model.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#7488]
The TODO lists for MobileNet-SSD model. Related to https://github.com/PaddlePaddle/Paddle/issues/7402

- [x] Develop depthwise convolution operator. https://github.com/PaddlePaddle/Paddle/pull/7885
- [x] Develop anchor_box_op/prior_box_op. https://github.com/PaddlePaddle/Paddle/pull/6150
- [x] Develop iou_similarity_op. ( Intersection over Union (IOU) operator ) https://github.com/PaddlePaddle/Paddle/pull/7566
- [x] Develpp bipartite_match_op. (bipartite match operator) https://github.com/PaddlePaddle/Paddle/pull/7695
- [x] Develop box_coder_op. https://github.com/PaddlePaddle/Paddle/pull/7922
- [x] Develop mine_hard_examples_op. https://github.com/PaddlePaddle/Paddle/pull/7679
- [x] Develop target_assign_op. https://github.com/PaddlePaddle/Paddle/pull/8193
- [x] Develop batch_multiclass_nms_op. https://github.com/PaddlePaddle/Paddle/pull/7953
- [x] Develop mAP evalutor. https://github.com/PaddlePaddle/Paddle/pull/6588
- [x] Wrap Python API for depthwise convolution operator.
- [x] Wrap Python API for anchor_box_op/prior_box_op. (prior_box_op #8265)
- [x] Wrap Python API for iou_similarity_op. https://github.com/PaddlePaddle/Paddle/pull/8385
- [x] Wrap Python API for bipartite_match_op. https://github.com/PaddlePaddle/Paddle/pull/8385
- [x] Wrap Python API for box_coder_op. https://github.com/PaddlePaddle/Paddle/pull/8385
- [x] Wrap Python API for mine_hard_examples_op. https://github.com/PaddlePaddle/Paddle/pull/8385
- [x] Wrap Python API for target_assign_op. https://github.com/PaddlePaddle/Paddle/pull/8385
- [x] Wrap Python API for batch_multiclass_nms_op.  https://github.com/PaddlePaddle/Paddle/issues/8380
- [x] Wrap Python API for ssd_multibox_loss_op. https://github.com/PaddlePaddle/Paddle/pull/8385
- [x] Test ssd_multibox_loss. https://github.com/PaddlePaddle/Paddle/issues/8626
- [x] Wrap Python API for ssd_detection_output_op. https://github.com/PaddlePaddle/Paddle/issues/8380
- [x] Test ssd_detection_output.  https://github.com/PaddlePaddle/Paddle/issues/8687
- [x] Wrap Python API for mAP evalutor. https://github.com/PaddlePaddle/Paddle/issues/8572
- [x] Verify MobileNet model. https://github.com/PaddlePaddle/models/pull/634#issuecomment-364344193
- [x] Verify SSD model.
- [x] Verify MobileNet-SSD model.
