### ISSUE TITLE
Bazel Build

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#792]
Related Issue #681, #819, #818

The issue used for tracking Paddle `feature/bazel_build` develop status.

Problems:
* [ ] How bazel read command line flags or environment variable? It is very useful for Paddle to make various binary file. Such as WITH_GPU, WITH_AVX, WITH_DOUBLE, etc. See [here](https://github.com/PaddlePaddle/Paddle/blob/feature/bazel_build/build_tools/build_config.bzl#L4).

* [ ] Currently, reference Python library just use a precompiled static library. It may be a critical defect. See [here](https://github.com/PaddlePaddle/Paddle/blob/feature/bazel_build/WORKSPACE#L34). Is there a better way to reference a third party library, without manually writing a bazel build for it? 

TODOs:

* [x] incorporate gtest and protobuf https://github.com/PaddlePaddle/Paddle/issues/816
* [x] incorporate glog and gflags https://github.com/PaddlePaddle/Paddle/issues/822
* [x] `paddle` python package
* [ ] paddle_proto module
    * [x] Remove m4 macro language when generating protobuf. Done with https://github.com/PaddlePaddle/Paddle/pull/846
* [x] logging using glog https://github.com/PaddlePaddle/Paddle/issues/869
* [ ] paddle_util module
   * Related ISSUE #793
   * Under developing. Maybe some new issues will be added.
* [ ] paddle_math module.
* [ ] gserver module.
* [ ] pserver module
* [ ] trainer module
* [ ] api module

**Comment by wangkuiyi** [comment]
@reyoung I am curious how does Tensorflow refer to Python libraries?

**Comment by wangkuiyi** [comment]
One thing to remind is that we should keep all third-party dependencies in a subdirectory, usually named `third_party`. A good example is: 

https://github.com/tensorflow/tensorflow/tree/master/third_party

This would allow us to inspect and manage all our third-party dependencies because any introduction of a new third-party dependency would have to go through a PR that adds a sub-directory and/or a .build/.bzl file into `thrid-party`.

**Comment by reyoung** [comment]
> it that because Tensorflow only builds itself as a library callable from Python, but not embedding Python interpreter into it, so we cannot learn from Tensorflow's BUILD files?

You're right. We cannot learn from Tensorflow's BUILD. To manually write a bazel build file for Python interpreter is a complicated job. So currently, we just give a prebuild binary for Python dependency.

> I noticed that you packed Python as a tarball. Can you share how did you do that?

I just copy my laptop system's library and header now. There is a personal [repository](https://github.com/reyoung/CompilePython27) for building static Python Interpreter.  I'm trying to refine this scripts, and then it can be used to make a full static tar.gz package for both Linux and MacOS.

**Comment by reyoung** [comment]
Closed because we choose cmake to manage paddle build
