### ISSUE TITLE
Paddle Matrix相关问题整理

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#857]
* [x] issue #746 编译单测时的warning
* [x] issue #703 重构class Matrix里面的一些计算API
* [x] issue #695 重构paddle/math/tests/
* [x] issue #676 paramReluBackwardDiff的CPU和GPU实现不完全一致
* [x] issue #675 Matrix::sequenceAvgForward的CPU实现GPU实现有差异
* [x] issue #338 Error sparse matrix mul
* [x] issue #294 CPU version of crossMapNormalBwd is not implemented
* [x] issue #330 Prediction with py_paddle and 'use_gpu=1'
