### ISSUE TITLE
Turn on the cmake flag WITH_DISTRIBUTE on CI system

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#9046]
it's better to cache the third-party package on CI so that we can improve CI performance and turn on `WITH_DISTRIBUTE` cmake flag as also.

We can't turn on `WITH_DISTRIBUTE` currently is just because building `gRPC` dependency would task very very long time.

**Comment by Yancey1989** [comment]
We can not turn on the cmake flag `WITH_DISTRIBUTE=ON` utile the following bug fixed:
- [ ] `test_send_recv` hung, #9315 
- [ ] buid failed on CI #9309 
- [ ] `test_send ` failed, #9292

**Comment by helinwang** [comment]
@Yancey1989 can you @ yourself on the ones you are working on? I will work on the not taken ones tomorrow.

**Comment by gongweibao** [comment]
Another one:
- [ ] Gurantee loss goes down: https://github.com/PaddlePaddle/Paddle/issues/9284

**Comment by Yancey1989** [comment]
Thanks @helinwang, I'll take #9315 : )

**Comment by gongweibao** [comment]
There are many hidden issues in https://github.com/PaddlePaddle/Paddle/wiki/PaddlePaddle-CI-Build-Scripts
- `$tp_cache_file` may be used  by many process concurrently, so it can't be modified by one process without `Critical Section`
- I think it may be better to cache some models with their version, such as `grpc` `boost` and so on. And the others do not need to cache them since their time is not long which we don't care.

So if you have a PR with the script, I can submit the upon comments to it.  @Yancey1989

**Comment by gongweibao** [comment]
Can we use a file with a sign to avoid copy and untar file?
https://github.com/PaddlePaddle/Paddle/wiki/PaddlePaddle-CI-Build-Scripts

**Comment by helinwang** [comment]
@putcn would love some help here in case you have bandwidth :D

**Comment by putcn** [comment]
I can work on #9309

**Comment by typhoonzero** [comment]
@Yancey1989 @putcn Can we close this now?

**Comment by Yancey1989** [comment]
Okay, will close this issue, we already turn on the cmake flag `WITH_DISTRIBUTE=ON` on the CI system.
