### ISSUE TITLE
Refine the sources in utils directory

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#956]
Currently, `paddle/utils` includes miscellaneous, irrelevant source code, which should be deleted or moved to other places.

For instance, dependency relationships:

 ```[utils <- cuda], [cuda <- utils]```
`initMain()` in `utils` dir depends on `hl_start()` in `cuda` dir, and vice versa .

After discussing with @reyoung @wangkuiyi, we reached a preliminary consensus to revise sources.

- [ ] ├── BarrierStat.cpp
- [ ] ├── BarrierStat.h
- [ ] ├── CMakeLists.txt
- [ ] ├── ClassRegistrar.h
- [x] ├── CommandLineParser.cpp   #989   @gangliao
- [x] ├── CommandLineParser.h       #989   @gangliao
- [ ] ├── CpuId.cpp                                ` runtime check flags for AVX`   @gangliao
- [ ] ├── CpuId.h             @gangliao
- [ ] ├── CustomStackTrace.cpp
- [ ] ├── CustomStackTrace.h
- [x] ├── DisableCopy.h                       #994 move into common.h @gangliao
- [x] ├── Excepts.cpp                            ` mac_os_x` #1075 @gangliao
- [x] ├── Excepts.h                                  @gangliao
- [ ] ├── Flags.cpp                                #852 @reyoung  
- [ ] ├── Flags.h                                    @reyoung  ` all global flags definitions, need to be removed.`
- [ ] ├── GlobalConstants.cpp             ` we do new API implementation. PassType -> Trainer.h,` 
- [ ] ├── GlobalConstants.h                 ` ParameterType -> Parameter.h`
- [ ] ├── Locks.h                                   ` some locks can be removed.`
- [ ] ├── Logging.cpp                           ` use gflags.h, Keep debug logging level`
- [ ] ├── Logging.h
- [ ] ├── PythonUtil.cpp                       ` /paddle/python`
- [ ] ├── PythonUtil.h
- [ ] ├── Queue.h                                  ` ThreadSafeQueue.h`
- [ ] ├── Stat.cpp                                  ` move registerTimer to  paddle/stats`
- [ ] ├── Stat.h
- [ ] ├── StringUtil.cpp
- [ ] ├── StringUtil.h
- [ ] ├── Thread.h                                 ` delete if not necessary`
- [ ] ├── ThreadLocal.cpp                    ` seems necessary, how about c++11 thread library?`
- [ ] ├── ThreadLocal.h
- [x] ├── TypeDefs.h                             ` FloatType.h`  #994 move into common.h @gangliao
- [ ] ├── Util.cpp
- [ ] ├── Util.h                                        ` split into several pieces`
- [ ] ├── Version.cpp                             ` delete or split`
- [ ] ├── Version.h
├── arch
│   ├── linux
│   │   └── Locks.cpp
│   └── osx
│       └── Locks.cpp
├── enable_virtualenv.c
├── enable_virtualenv.py
└── tests

**Comment by wangkuiyi** [comment]
Good to see this issue!  Are we going to create some sub-tasks and assign them to our team members? Thansk! @gangliao

**Comment by gangliao** [comment]
@wangkuiyi 
Firstly, I will do a typical sub-task fully based on our [c++ style](https://github.com/PaddlePaddle/cpp-primer-digest), discussing with our colleagues who want to involve and contribute. 

The continued follow-up development works and even the future C API will benefit a lot from this start point.

Thanks a lot.

**Comment by gangliao** [comment]
For `DisableCopy.h`, it might be changed to `common.h`
