### ISSUE TITLE
Fix CPPLint errors in Fluid Operators

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Paddle#9755]
Fix CPPLint errors in Fluid Operators found at `/Paddle/paddle/fluid/operators`

- [x] activation_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9776
- [x] adagrad_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9776
- [x] array_operator.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9776
- [x] assign_value_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9776
- [x] assign_value_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9776
- [x] auc_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9776
- [x] auc_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9776
- [x] average_accumulates_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9776
- [x] average_accumulates_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9776
- [x] batch_norm_op.cc:363 @sidgoyal78 #9800
- [x] batch_norm_op.cu.cc @sidgoyal78 #9800
- [x] batch_size_like.h @sidgoyal78 #9800
- [x] beam_search_decode_op.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9962
- [x] beam_search_decode_op.h  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9962
- [x] beam_search_decode_op_test.cc 
- [x] beam_search_op.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9962
- [x] beam_search_op.h  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9962
- [x] box_coder_op.cc @sidgoyal78 #9800
- [x] box_coder_op.cu @sidgoyal78 #9800
- [x] box_coder_op.h @sidgoyal78 #9800
- [x] channel_recv_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9753
- [x] chunk_eval_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9964
- [x] chunk_eval_op.h: @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9964
- [x] compare_op.cc @sidgoyal78 #9800
- [x] concat_op.cc @sidgoyal78 #9800
- [x] cond_op.h @sidgoyal78 #9800
- [x] conv_mkldnn_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9969
- [x] conv_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9969
- [x] conv_transpose_op.cc @sidgoyal78 #9800
- [x] conv_transpose_op.h @sidgoyal78 #9800
- [x] crf_decoding_op.h @sidgoyal78 #9800
- [x] crop_op.cc @sidgoyal78 #9800
- [x] crop_op.h @sidgoyal78 #9800
- [x] ctc_align_op.cu @sidgoyal78 #9837
- [x] ctc_align_op.h @sidgoyal78 #9837
- [x] detection_map_op.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9969
- [x] detection_map_op.h   @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9969
- [x] edit_distance_op.cu @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9969
- [x] elementwise_op.h @sidgoyal78 #9837
- [x] elementwise_op_function.h 
- [x] expand_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10000
- [x] expand_op.h  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10000
- [x] gather_op.cu @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10000
- [x] gather_op.h  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10000
- [x] gather_test.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10000
- [x] get_places_op.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10000
- [x] go_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9753
- [x] gru_op.cc @sidgoyal78 #9837
- [x] gru_op.h @sidgoyal78 #9837
- [x] im2sequence_op.cc @sidgoyal78 #9837
- [x] im2sequence_op.h @sidgoyal78 #9837
- [x] label_smooth_op.cc @sidgoyal78 #9837
- [x] linear_chain_crf_op.h  @sidgoyal78 #9837
- [x] listen_and_serv_op.cc 
- [x] listen_and_serv_op.h
- [x] lod_reset_op.cc @sidgoyal78 #9837
- [x] lod_reset_op.h @sidgoyal78 #9837
- [x] logical_op.cc @sidgoyal78 #9837
- [x] lrn_op.cc @sidgoyal78 #9837
- [x] lstm_op.cc @sidgoyal78 #9837
- [x] lstm_op.h @sidgoyal78 #9837
- [x] lstm_unit_op.cu @sidgoyal78 #9837
- [x] lstmp_op.cc @sidgoyal78 #9837
- [x] lstmp_op.h @sidgoyal78 #9837
- [x] matmul_op.cc @sidgoyal78 #9837
- [x] matmul_op.h @sidgoyal78 #9837
- [x] maxout_op.cc @sidgoyal78 #9837
- [x] minus_op.cc @sidgoyal78 #9837
- [x] mkldnn_activation_op.h
- [x] momentum_op.cu @sidgoyal78 #9837
- [x] mul_op.cc @sidgoyal78 #9837
- [x] multiclass_nms_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10032/
- [x] nccl_op.cu.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10032/
- [x] nce_op.cc
- [x] nce_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10032/
- [x] pad_op.cc
- [x] pad_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] pool_mkldnn_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] pool_op.cc
- [x] pool_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] pool_with_index_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] pool_with_index_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] prefetch_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] prelu_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] print_op.cc @sidgoyal78 https://github.com/PaddlePaddle/Paddle/pull/10070
- [x] prior_box_op.cc
- [x] prior_box_op.cu
- [x] prior_box_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] rank_loss_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] recv_op.cc:22 @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] reduce_op.cc
- [x] reduce_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10032/
- [x] roi_pool_op.cu
- [x] roi_pool_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] save_load_combine_op_test.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/10032/
- [x] scale_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] scatter_op.cu @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] scatter_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] scatter_test.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] select_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9753
- [x] send_barrier_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] send_op.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] send_recv_op_test.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] send_recv_util.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] send_vars_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] sequence_concat_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] sequence_conv_op.cc 
- [x] sequence_conv_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] sequence_erase_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] sequence_erase_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] sequence_pool_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] sequence_pool_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] sequence_softmax_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] softmax_mkldnn_op.cc @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] split_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9826
- [x] spp_op.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
- [x] spp_op.h  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
- [x] strided_memcpy.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] sum_op.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
- [x] sum_op.h  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
- [x] top_k_op.cu @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9828/
- [x] top_k_op.h  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
- [x] transpose_op.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
- [x] transpose_op.h  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
- [x] unpool_op.cc  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
- [x] unpool_op.h  @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
- [x] warpctc_op.h @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/9779
